name: hamon_test
description: "A new Flutter project."


publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  flutter_bloc: ^8.1.6
  get_it: ^7.7.0
  internet_connection_checker_plus: ^2.3.0
  go_router: ^14.2.1
  dio: ^5.5.0+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/images/

  fonts:
    - family: SF-Pro
      fonts:
        - asset: assets/SF-Pro-Dispaly-Bold.otf
        - asset: assets/SF-Pro-Dispaly-Regular.otf
        - asset: assets/SF-Pro-Text-Regular.otf

  
  
  
  

  
  

  
  

  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
